[build]
target = "riscv64imac-unknown-none-elf"

# rustflags = ["-C", "link-arg=-nostartfiles"]
rustflags = [
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-nostdlib",
    "-C",
    "link-arg=-static",
    # "-C",
    # "link-arg=-Ttext-segment,0x80000000",
]


[target.'cfg(all)']
# rustflags = ["-C", "link-arg=-nostartfiles"]
