[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build_plugin]
command = "cargo"
args = ["build"]

[tasks.build_plugin_test_rs]
command = "cargo"
args = ["build"] #, "--target", "riscv64imac-unknown-none-elf", "--release"]
cwd = "plugin_test"

[tasks.build_plugin_test]
command = "make"
args = ["-C", "test", "plugin_test"]

# [tasks.spike]
# command = "spike"
# args = [
#     # "--extlib=${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/libplugin.dylib",
#     "--extlib=${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/plugin",
#     "--device=test_mmio_plugin,0x10000000,argument",
#     # "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/riscv64imac-unknown-none-elf/debug/plugin_test",
#     "./test/plugin_test",
# ]
# dependencies = ["build_plugin", "build_plugin_test_rs", "build_plugin_test"]

[tasks.spike]
command = "/Volumes/src_cs/riscv/riscv-isa-sim/spike"
args = [
    "-m32",
    "--extlib=target/debug/plugin",
    "--device=uart_plugin,0x10000000,argument",
    "plugin_test/target/riscv64gc-unknown-none-elf/debug/plugin_test",
]
dependencies = ["build_plugin", "build_plugin_test_rs"]
