[target.'cfg(target_os = "macos")']
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    # "-C",
    # "link-arg=-o",
    # "-C",
    # "link-arg=plugin.so",
]

[target.riscv64imac-unknown-none-elf]
# rustflags = ["-C", "link-arg=-nostartfiles"]
rustflags = [
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "link-arg=-nostdlib",
    "-C",
    "link-arg=-static",
    # "-C",
    # "link-arg=-Ttext-segment,0x80000000",
]
